### ISSUE TITLE
[urgent] Setuptools update to 65.6.0 makes installing zict fail

### ISSUE THREAD

**Issue by tulbureandreit** [dask/zict#73] opened 2022-11-23 08:11 UTC
Hi,

TLDR, setuptools just updated to 65.6.0 and it breaks our docker dev flows. It tries installing zict and it fails.

Could you PIN the version on 65.5.1? It`s only true if you have numpy <=1.23.0, as far as I can see.

**Comment by jrbourbeau** [comment] 2022-11-23 17:51
Thanks for reporting @tulbureandreit. I'm not able to reproduce with the following steps:

- Create a fresh conda environment with `mamba create --name test python=3.9 numpy=1.23.0`
    - This pulled in `setuptools=65.5.1`, which is, I suspect the problematic release and there's a typo in your original comment (though maybe I'm wrong here). 
- `mamba activate test`
- `pip install zict`

This ran successfully and installed the latest `zict=2.2.0` release. I then manually installed `setuptools=65.5.0` and was able to until and then reinstall `zict` successfully.

More information about your setup would be helpful? How are you installing things?

**Comment by tulbureandreit** [comment] 2022-11-23 20:54
65.6.0 is the version with a problem, when using numpy <= 1.23.0 for zict =2.2.0 and statsmodels =0.13.0

**Comment by jrbourbeau** [comment] 2022-11-23 22:11
It looks like this is a `setuptools` issue and not a `zict` issue (xref https://github.com/pypa/setuptools/issues/3693). There's also a fresh 65.6.2 release that should resolve that issue https://github.com/pypa/setuptools/issues/3693#issuecomment-1325363410. Could you try that new `setuptools` release?

**Comment by tulbureandreit** [comment] 2022-11-24 06:08
Will try it. I resolved it with SETUPTOOLS_USE_DISTUTILS=stdlib poetry install

**Comment by jrbourbeau** [comment] 2022-11-30 22:41
Going to close this issue as resolved via the upstream `setuptools` fix. Though @tulbureandreit feel free to re-open if that's not the case

**Closed by jrbourbeau** 2022-11-30 22:41 UTC
